// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChfQFOGiD-de6-V7jTMTz5u0UosnAFw_0',
    appId: '1:460065792056:web:7cca8ff50ba914509986cd',
    messagingSenderId: '460065792056',
    projectId: 'firechatapp-678f8',
    authDomain: 'firechatapp-678f8.firebaseapp.com',
    storageBucket: 'firechatapp-678f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4GG6ydqgLCYsCKSJC_OSMusr-miDe96c',
    appId: '1:460065792056:android:6f1e7004691324699986cd',
    messagingSenderId: '460065792056',
    projectId: 'firechatapp-678f8',
    storageBucket: 'firechatapp-678f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDItDfdXVkPF-qpIuYrSeXkSJEM30cFeWQ',
    appId: '1:460065792056:ios:4b1f9afa9d04aeba9986cd',
    messagingSenderId: '460065792056',
    projectId: 'firechatapp-678f8',
    storageBucket: 'firechatapp-678f8.firebasestorage.app',
    iosBundleId: 'com.finedev.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDItDfdXVkPF-qpIuYrSeXkSJEM30cFeWQ',
    appId: '1:460065792056:ios:4b1f9afa9d04aeba9986cd',
    messagingSenderId: '460065792056',
    projectId: 'firechatapp-678f8',
    storageBucket: 'firechatapp-678f8.firebasestorage.app',
    iosBundleId: 'com.finedev.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChfQFOGiD-de6-V7jTMTz5u0UosnAFw_0',
    appId: '1:460065792056:web:fe575834ef34619a9986cd',
    messagingSenderId: '460065792056',
    projectId: 'firechatapp-678f8',
    authDomain: 'firechatapp-678f8.firebaseapp.com',
    storageBucket: 'firechatapp-678f8.firebasestorage.app',
  );

}